name: Archon – Close task on merge

on:
  pull_request:
    types: [closed]

jobs:
  archon-close-task:
    if: ${{ github.event.pull_request.merged == true && contains(join(github.event.pull_request.labels.*.name, ','), 'core-update') }}
    runs-on: ubuntu-latest
    steps:
      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install pnpm
        run: npm i -g pnpm@9
      - name: Install workspace deps (for tools)
        run: pnpm install --frozen-lockfile
      - name: Mark Archon task as done
        env:
          ARCHON_URL: ${{ secrets.ARCHON_URL }}
          ARCHON_TOKEN: ${{ secrets.ARCHON_TOKEN }}
        run: |
          node tools/archon-task.mjs update \
            --externalId "ops/core-update-${{ github.event.pull_request.head.sha }}" \
            --status done || echo "Archon update skipped (not configured)"
        continue-on-error: true
